services:
  web:
    build: .
    container_name: almacen-web
    ports:
      - "3005:80"
    environment:
      - APACHE_RUN_USER_ID=1000
      - APACHE_RUN_GROUP_ID=1000
    volumes:
      - .:/var/www/html
    restart: unless-stopped
